name: Deploy to Windows Server (IIS)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Copy files to Windows Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WINDOWS_SERVER_IP }}
          username: ${{ secrets.WINDOWS_SERVER_USER }}
          password: ${{ secrets.WINDOWS_SERVER_PASS }}
          source: "./publish/*"
          target: "C:/inetpub/wwwroot/sampleapi"

      - name: Restart IIS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_SERVER_IP }}
          username: ${{ secrets.WINDOWS_SERVER_USER }}
          password: ${{ secrets.WINDOWS_SERVER_PASS }}
          script: |
            iisreset
